services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: ./mysite
    command: python mysite/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
      - migration
  migration:
    build: ./mysite
    command: python mysite/manage.py migrate
    volumes:
      - .:/code
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
  frontend:
    build: ./myanimelistfe
    ports:
      - 3000:3000
    stdin_open: true
    # volumes:
    #   - ./frontend:/usr/src/app
    #   - /usr/src/app/node_modules
    restart: always
    # networks:
    #   - react-express
    depends_on:
      - web